-- サーバー起動時のテストデータ初期化
-- H2データベース用の初期データ

-- BORROWERSテーブル用の初期データ
INSERT INTO BORROWERS (ID, COMPANY_ID, CREATED_AT, CREDIT_LIMIT, CREDIT_RATING, EMAIL, NAME, PHONE_NUMBER, STATUS, UPDATED_AT, VERSION)
VALUES 
(1, null, CURRENT_TIMESTAMP, 1000.00, 'A', 'borrower01@example.com', 'borrower01', '03-1111-1111', 'ACTIVE', CURRENT_TIMESTAMP, 0),
(2, null, CURRENT_TIMESTAMP, 2000.00, 'A', 'borrower02@example.com', 'borrower02', '03-2222-2222', 'ACTIVE', CURRENT_TIMESTAMP, 0);

-- INVESTORSテーブル用の初期データ
INSERT INTO INVESTORS (ID, COMPANY_ID, CREATED_AT, CURRENT_INVESTMENT_AMOUNT, EMAIL, INVESTMENT_CAPACITY, INVESTOR_TYPE, IS_ACTIVE, NAME, PHONE_NUMBER, STATUS, UPDATED_AT, VERSION)
VALUES 
(1, null, CURRENT_TIMESTAMP, 0.00, 'investor01@example.com', 10000.00, 'LEAD_BANK', TRUE, 'investor01', '03-1111-1111', 'ACTIVE', CURRENT_TIMESTAMP, 0),
(2, null, CURRENT_TIMESTAMP, 0.00, 'investor02@example.com', 20000.00, 'BANK', TRUE, 'investor02', '03-2222-2222', 'ACTIVE', CURRENT_TIMESTAMP, 0),
(3, null, CURRENT_TIMESTAMP, 0.00, 'investor03@example.com', 30000.00, 'INDIVIDUAL', TRUE, 'investor03', '03-3333-3333', 'ACTIVE', CURRENT_TIMESTAMP, 0),
(4, null, CURRENT_TIMESTAMP, 0.00, 'investor04@example.com', 40000.00, 'LEAD_BANK', TRUE, 'investor04', '03-4444-4444', 'ACTIVE', CURRENT_TIMESTAMP, 0),
(5, null, CURRENT_TIMESTAMP, 0.00, 'investor05@example.com', 50000.00, 'BANK', TRUE, 'investor05', '03-5555-5555', 'ACTIVE', CURRENT_TIMESTAMP, 0),
(6, null, CURRENT_TIMESTAMP, 0.00, 'investor06@example.com', 60000.00, 'BANK', TRUE, 'investor06', '03-6666-6666', 'ACTIVE', CURRENT_TIMESTAMP, 0);

-- SYNDICATESテーブル用の初期データ
INSERT INTO SYNDICATES (ID, BORROWER_ID, CREATED_AT, LEAD_BANK_ID, NAME, UPDATED_AT, VERSION)
VALUES 
(1, 1, CURRENT_TIMESTAMP, 1, 'syndicate01', CURRENT_TIMESTAMP, 0);

-- SYNDICATE_MEMBERSテーブル用の初期データ
INSERT INTO SYNDICATE_MEMBERS (SYNDICATE_ID, INVESTOR_ID)
VALUES 
(1, 2),
(1, 3);

-- FACILITIESテーブル用の初期データ
INSERT INTO FACILITIES (ID, COMMITMENT, CREATED_AT, CURRENCY, END_DATE, INTEREST_TERMS, START_DATE, STATUS, SYNDICATE_ID, UPDATED_AT, VERSION)
VALUES 
(1, 1000.00, CURRENT_TIMESTAMP, 'JPY', '2026-07-04', 'TIBOR +0.2%', '2025-07-04', 'DRAFT', 1, CURRENT_TIMESTAMP, 0);

-- TRANSACTIONテーブル用の初期データ（FACILITY_INVESTMENT用）
INSERT INTO TRANSACTION (ID, FACILITY_ID, BORROWER_ID, TRANSACTION_DATE, TRANSACTION_TYPE, STATUS, AMOUNT, CREATED_AT, UPDATED_AT, VERSION)
VALUES 
(1, 1, 1, '2025-07-04', 'FACILITY_INVESTMENT', 'COMPLETED', 250.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
(2, 1, 1, '2025-07-04', 'FACILITY_INVESTMENT', 'COMPLETED', 750.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);

-- FACILITY_INVESTMENTテーブル用の初期データ
INSERT INTO FACILITY_INVESTMENT (INVESTOR_ID, ID)
VALUES 
(2, 1),
(3, 2);

-- FACILITY_SHARE_PIESテーブル用の初期データ
INSERT INTO FACILITY_SHARE_PIES (ID, CREATED_AT, INVESTOR_ID, SHARE, UPDATED_AT, FACILITY_ID)
VALUES 
(1, CURRENT_TIMESTAMP, 2, 0.2500, CURRENT_TIMESTAMP, 1),
(2, CURRENT_TIMESTAMP, 3, 0.7500, CURRENT_TIMESTAMP, 1);